// Studio Engine - Handles Post-Production (Zooming, Clicks, Export)
// Uses Rust-based zoom engine via Tauri IPC for desktop
// Falls back to simple playback for browser mode

import { isTauri } from './tauri-bridge';
import { InteractionAnalyzer } from './zoom/InteractionAnalyzer';
import { renderFrame } from './rendering/renderFrame';

const FRAME_SCALE = 0.82;
const TITLE_BAR_HEIGHT = 36;

export class StudioEngine {
    constructor(canvas, videoElement, blob, clicks = [], duration = null, mouseMoves = [], options = {}) {
        console.log('[Studio] Initializing with', clicks.length, 'clicks, duration:', duration);

        this.canvas = canvas;
        this.ctx = canvas.getContext('2d', { alpha: false, desynchronized: true });
        this.video = videoElement;

        // Cached background gradient (rebuilt only when bg changes or canvas resizes)
        this._cachedBg = null;
        this._cachedBgKey = '';

        this.blob = blob;
        this.clicks = clicks;
        this.explicitDuration = duration;
        this.mouseMoves = mouseMoves;

        // Webcam PiP Video & Settings
        this.webcamBlob = options.webcamBlob || null;
        this.webcamOffset = options.webcamOffset || 0;
        this.webcamVideo = null;
        this.webcamSettings = options.webcamSettings || {
            enabled: Boolean(options.webcamBlob),
            shape: 'circle',
            position: 'bottom-right',
            size: 0.22,
            mirrored: false,
        };
        if (this.webcamBlob) {
            this.webcamVideo = document.createElement('video');
            this.webcamVideo.src = typeof this.webcamBlob === 'string' ? this.webcamBlob : URL.createObjectURL(this.webcamBlob);
            this.webcamVideo.muted = true;
            this.webcamVideo.playsInline = true;
            this.webcamVideo.load();
        }

        // Multi-Track Audio (WASAPI system loopback + mic)
        this.systemAudioUrl = options.systemAudioUrl || null;
        this.micAudioUrl = options.micAudioUrl || null;
        this.systemAudio = null;
        this.micAudio = null;
        if (this.systemAudioUrl) {
            this.systemAudio = new Audio(this.systemAudioUrl);
            this.systemAudio.preload = 'auto';
        }
        if (this.micAudioUrl) {
            this.micAudio = new Audio(this.micAudioUrl);
            this.micAudio.preload = 'auto';
        }

        // Multi-Track Audio Mixer (Volume, Mute & Smart Voice Ducking)
        this.systemAudioVolume = options.systemAudioVolume ?? 1.0;
        this.micAudioVolume = options.micAudioVolume ?? 1.2;
        this.isSystemAudioMuted = options.isSystemAudioMuted ?? false;
        this.isMicAudioMuted = options.isMicAudioMuted ?? false;
        this.autoDuck = options.autoDuck ?? true;
        this.updateAudioVolumes();

        // Auto-Captions Subtitles
        this.captions = options.captions || [];
        this.captionsEnabled = options.captionsEnabled ?? true;

        // Annotations Layer
        this.annotations = options.annotations || [];

        // Custom Background Image
        this.customBackgroundImage = options.customBackgroundImage || null;
        this.cursorTheme = options.cursorTheme || 'macos';
        this.cursorScale = options.cursorScale ?? 1.0;
        this.splineSmoothing = options.splineSmoothing ?? true;

        // Semantic Interaction Analyzer & Focus Track
        this.interactionAnalyzer = new InteractionAnalyzer();
        this.focusSegments = options.focusSegments ?? this.interactionAnalyzer.analyze(
            this.clicks,
            this.mouseMoves,
            this.explicitDuration || 10
        );

        // Camera state — starts FULLY panned out (scale 1.0)
        this.camera = { x: 0.5, y: 0.5, scale: 1 };

        // Cursor state from Rust
        this.cursorState = { x: 0.5, y: 0.5, opacity: 0.0, click_progress: 0.0, motion: 0.0 };

        // Zoom segments (generated by Rust)
        this.zoomSegments = [];

        // Tauri mode detection
        this.isTauri = false;
        this.tauriReady = false;

        // Customizable settings
        this.background = 'bigSur';
        this.startPosition = 'center';
        this.trimStart = 0;
        this.trimEnd = 0;
        this.showCursor = options.showCursor ?? ((this.mouseMoves && this.mouseMoves.length > 0) || (this.clicks && this.clicks.length > 0));
        this.zoomLevel = 2.0;

        // Precomputed frames for export (array of FrameState from Rust)
        this.precomputedFrames = null;

        this.isPlaying = false;
        this.animationFrame = null;

        this._initTauri();
        this.init();
    }

    async _initTauri() {
        try {
            if (!isTauri()) {
                console.log('[Studio] Browser mode — simple playback (no zoom engine)');
                return;
            }
            const { invoke } = await import('@tauri-apps/api/core');
            this.isTauri = true;
            this.tauriInvoke = invoke;
            console.log('[Studio] Tauri mode — using Rust zoom engine');

            // Generate zoom segments in Rust
            await this._generateSegments();
            this.tauriReady = true;
        } catch {
            console.log('[Studio] Browser fallback — no Tauri available');
        }
    }

    async _generateSegments() {
        if (!this.tauriInvoke) return;

        try {
            const clickEvents = this.clicks.map(c => ({
                time: c.time,
                x: c.x,
                y: c.y,
                down: true,
            }));

            const moveEvents = (this.mouseMoves || []).map(m => ({
                time: m.time,
                x: m.x,
                y: m.y,
            }));

            const durationMs = (this.explicitDuration || 10) * 1000;

            this.zoomSegments = await this.tauriInvoke('generate_zoom_segments', {
                clicks: clickEvents,
                moves: moveEvents,
                durationMs: durationMs,
            });

            console.log('[Studio] Rust generated', this.zoomSegments.length, 'zoom segments');
        } catch (e) {
            console.error('[Studio] Segment generation failed:', e);
            this.zoomSegments = [];
        }
    }

    init() {
        console.log('[Studio] init() called');
        if (typeof this.blob === 'string') {
            this.video.src = this.blob;
        } else if (this.blob instanceof Blob) {
            this.video.src = URL.createObjectURL(this.blob);
        }
        this.video.muted = true; // Essential: muted allows instant first-frame decoding without browser autoplay block
        try {
            this.video.load();
        } catch (e) {}

        const onFrameReady = () => {
            console.log('[Studio] Video frame ready, readyState:', this.video.readyState, 'duration:', this.video.duration);
            this.setAspectRatio(this.aspectRatio || '16:9');

            if (this.explicitDuration) {
                this.videoDuration = this.explicitDuration;
            } else if (Number.isFinite(this.video.duration) && this.video.duration > 0) {
                this.videoDuration = this.video.duration;
            } else {
                const lastClick = this.clicks[this.clicks.length - 1];
                this.videoDuration = lastClick ? (lastClick.time / 1000 + 2) : 10;
            }
            this.drawFrame();
        };

        this.video.onloadedmetadata = () => {
            onFrameReady();
            // Nudge decoder to decode frame 0
            try {
                if (this.video.currentTime === 0) {
                    this.video.currentTime = 0.001;
                }
            } catch (e) {}
        };
        this.video.onloadeddata = onFrameReady;
        this.video.oncanplay = onFrameReady;

        this.video.onplay = () => {
            this.isPlaying = true;
            this.renderLoop();
        };
        this.video.onpause = () => {
            this.isPlaying = false;
            cancelAnimationFrame(this.animationFrame);
        };
        this.video.onended = () => {
            this.isPlaying = false;
        };
        this.video.onseeked = () => {
            if (this.webcamVideo) {
                this.webcamVideo.currentTime = Math.max(0, this.video.currentTime + (this.webcamOffset || 0));
            }
            this.drawFrame();
        };
        this.video.ontimeupdate = () => {
            if (this.webcamVideo && Math.abs(this.webcamVideo.currentTime - (this.video.currentTime + (this.webcamOffset || 0))) > 0.25) {
                this.webcamVideo.currentTime = Math.max(0, this.video.currentTime + (this.webcamOffset || 0));
            }
        };

        if (this.video.readyState >= 1) {
            onFrameReady();
        }
    }

    play() {
        this.video.muted = false;
        this.video.play().catch(e => console.error('[Studio] Play failed:', e));
        if (this.webcamVideo) {
            this.webcamVideo.currentTime = Math.max(0, this.video.currentTime + (this.webcamOffset || 0));
            this.webcamVideo.play().catch(() => {});
        }
        if (this.systemAudio) {
            this.systemAudio.currentTime = this.video.currentTime;
            this.systemAudio.play().catch(() => {});
        }
        if (this.micAudio) {
            this.micAudio.currentTime = this.video.currentTime;
            this.micAudio.play().catch(() => {});
        }
    }

    pause() {
        this.video.pause();
        if (this.webcamVideo) {
            this.webcamVideo.pause();
        }
        if (this.systemAudio) {
            this.systemAudio.pause();
        }
        if (this.micAudio) {
            this.micAudio.pause();
        }
    }

    seek(targetTime) {
        if (this.video) {
            this.video.currentTime = targetTime;
        }
        if (this.webcamVideo) {
            this.webcamVideo.currentTime = Math.max(0, targetTime + (this.webcamOffset || 0));
        }
        if (this.systemAudio) {
            this.systemAudio.currentTime = targetTime;
        }
        if (this.micAudio) {
            this.micAudio.currentTime = targetTime;
        }
        this.resetCamera();
        this.drawFrame();
    }

    setWebcamBlob(blob, offset = 0) {
        if (this.webcamVideo) {
            URL.revokeObjectURL(this.webcamVideo.src);
            this.webcamVideo.removeAttribute('src');
            this.webcamVideo.load();
            this.webcamVideo = null;
        }
        this.webcamBlob = blob;
        this.webcamOffset = offset;
        if (this.webcamBlob) {
            this.webcamVideo = document.createElement('video');
            this.webcamVideo.src = URL.createObjectURL(this.webcamBlob);
            this.webcamVideo.muted = true;
            this.webcamVideo.playsInline = true;
            this.webcamVideo.load();
        }
        this.drawFrame();
    }

    setSystemAudioVolume(vol) {
        this.systemAudioVolume = Math.max(0, Math.min(1.5, vol));
        this.updateAudioVolumes();
    }

    setMicAudioVolume(vol) {
        this.micAudioVolume = Math.max(0, Math.min(2.0, vol));
        this.updateAudioVolumes();
    }

    setSystemAudioMuted(muted) {
        this.isSystemAudioMuted = Boolean(muted);
        this.updateAudioVolumes();
    }

    setMicAudioMuted(muted) {
        this.isMicAudioMuted = Boolean(muted);
        this.updateAudioVolumes();
    }

    setAutoDuck(enabled) {
        this.autoDuck = Boolean(enabled);
    }

    updateAudioVolumes() {
        if (this.systemAudio) {
            this.systemAudio.volume = this.isSystemAudioMuted ? 0 : Math.max(0, Math.min(1, this.systemAudioVolume));
        }
        if (this.micAudio) {
            // Scale mic volume (default max 1.0 on standard HTMLAudioElement)
            this.micAudio.volume = this.isMicAudioMuted ? 0 : Math.max(0, Math.min(1, this.micAudioVolume > 1.0 ? 1.0 : this.micAudioVolume));
        }
    }

    resetCamera() {
        this.camera = { x: 0.5, y: 0.5, scale: 1 };
        this.cursorState = { x: 0.5, y: 0.5, opacity: 0.0, click_progress: 0.0, motion: 0.0 };
    }

    getFocusSegments() {
        return this.focusSegments || [];
    }

    setFocusSegments(segments) {
        this.focusSegments = segments;
        this.drawFrame();
    }

    deleteFocusSegment(id) {
        this.focusSegments = (this.focusSegments || []).filter(s => s.id !== id);
        this.drawFrame();
    }

    updateFocusSegment(id, updates) {
        const seg = (this.focusSegments || []).find(s => s.id === id);
        if (seg) {
            Object.assign(seg, updates);
            this.drawFrame();
        }
    }

    addFocusSegment(segment) {
        if (!this.focusSegments) this.focusSegments = [];
        this.focusSegments.push(segment);
        this.focusSegments.sort((a, b) => a.startTime - b.startTime);
        this.drawFrame();
    }

    async addZoom(timeSec, x = 0.5, y = 0.5, scale = 1.8) {
        const duration = this.videoDuration || this.explicitDuration || 10;
        const startTime = Math.max(0, Math.min(timeSec, duration - 0.1));
        this.addFocusSegment({
            id: crypto.randomUUID(),
            startTime,
            endTime: Math.min(duration, startTime + 2.5),
            targetX: Math.max(0, Math.min(1, x)),
            targetY: Math.max(0, Math.min(1, y)),
            zoomScale: scale,
            reason: 'manual',
            sceneMode: 'zoom',
        });
    }

    updateClick(index, updates) {
        if (index < 0 || index >= this.clicks.length) return;
        Object.assign(this.clicks[index], updates);
        this._generateSegments().then(() => {
            if (!this.isPlaying) {
                this.updateCamera();
                this.drawFrame();
            }
        });
    }

    resolveClick(normX, normY) {
        const Px = normX * this.canvas.width;
        const Py = normY * this.canvas.height;
        const P1x = Px - this.canvas.width / 2;
        const P1y = Py - this.canvas.height / 2;
        const P2x = P1x / this.camera.scale;
        const P2y = P1y / this.camera.scale;
        const vw = this.canvas.width * FRAME_SCALE;
        const vRatio = this.video.videoHeight / this.video.videoWidth;
        const vh = vw * vRatio;
        const totalHeight = vh + TITLE_BAR_HEIGHT;
        const panX = (this.camera.x - 0.5) * vw;
        const panY = (this.camera.y - 0.5) * totalHeight;
        const P3x = P2x + panX;
        const P3y = P2y + panY;
        const winX = -vw / 2;
        const winY = -totalHeight / 2;
        const videoX = winX;
        const videoY = winY + TITLE_BAR_HEIGHT;
        const relX = P3x - videoX;
        const relY = P3y - videoY;
        const finalX = relX / vw;
        const finalY = relY / vh;
        return {
            x: Math.max(0, Math.min(1, finalX)),
            y: Math.max(0, Math.min(1, finalY))
        };
    }

    renderLoop() {
        let frameCount = 0;
        const loop = () => {
            frameCount++;
            if (this.video) {
                this._applyPlaybackRate(this.video.currentTime);
            }
            this.updateCamera();
            this.drawFrame();
            if (this.isPlaying) this.animationFrame = requestAnimationFrame(loop);
        };
        loop();
    }

    _applyPlaybackRate(curTimeSec) {
        if (!this.video) return;
        const seg = (this.focusSegments || []).find(s => curTimeSec >= s.startTime && curTimeSec <= s.endTime);
        const targetRate = (seg && seg.speed) ? seg.speed : 1.0;
        if (Math.abs(this.video.playbackRate - targetRate) > 0.05) {
            this.video.playbackRate = targetRate;
            if (this.webcamVideo) {
                this.webcamVideo.playbackRate = targetRate;
            }
            if (this.systemAudio) {
                this.systemAudio.playbackRate = targetRate;
            }
            if (this.micAudio) {
                this.micAudio.playbackRate = targetRate;
            }
        }
    }

    dispose() {
        this.isPlaying = false;
        if (this.animationFrame) {
            cancelAnimationFrame(this.animationFrame);
            this.animationFrame = null;
        }
        if (this.video) {
            this.video.pause();
            this.video.onloadedmetadata = null;
            this.video.onloadeddata = null;
            this.video.oncanplay = null;
            this.video.ontimeupdate = null;
            this.video.onplay = null;
            this.video.onpause = null;
            this.video.onended = null;
            this.video.onseeked = null;
        }
        if (this.webcamVideo) {
            this.webcamVideo.pause();
            this.webcamVideo.src = '';
            this.webcamVideo = null;
        }
        if (this.systemAudio) {
            this.systemAudio.pause();
            this.systemAudio.src = '';
            this.systemAudio = null;
        }
        if (this.micAudio) {
            this.micAudio.pause();
            this.micAudio.src = '';
            this.micAudio = null;
        }
    }

    async updateCamera() {
        const currentMs = this.video.currentTime * 1000;

        if (this.isTauri && this.tauriReady) {
            try {
                // Single Rust call for both zoom and cursor state
                const state = await this.tauriInvoke('evaluate_frame', {
                    segments: this.zoomSegments,
                    moves: (this.mouseMoves || []).map(m => ({ time: m.time, x: m.x, y: m.y })),
                    clicks: this.clicks.map(c => ({ time: c.time, x: c.x, y: c.y, down: true })),
                    timeMs: currentMs,
                });

                this.camera = {
                    x: state.zoom.x,
                    y: state.zoom.y,
                    scale: state.zoom.scale,
                };
                this.cursorState = state.cursor;
            } catch (e) {
                // Fallback: no zoom
                this.camera = { x: 0.5, y: 0.5, scale: 1 };
            }
        } else {
            // Browser mode: no zoom, just basic cursor position from raw data
            this.camera = { x: 0.5, y: 0.5, scale: 1 };
            this._updateBrowserCursor(currentMs);
        }
    }

    // Simple browser fallback cursor (no spring, no zoom)
    _updateBrowserCursor(timeMs) {
        if (!this.mouseMoves || this.mouseMoves.length === 0) {
            this.cursorState = { x: 0.5, y: 0.5, opacity: 0.0, click_progress: 0.0, motion: 0.0 };
            return;
        }

        // Find nearest move
        let bestMove = this.mouseMoves[0];
        for (const m of this.mouseMoves) {
            if (m.time <= timeMs) bestMove = m;
            else break;
        }

        this.cursorState = {
            x: bestMove.x,
            y: bestMove.y,
            opacity: 1.0,
            click_progress: 0.0,
            motion: 0.0,
        };
    }

    // Static background definitions (created once, not per-frame)
    static BACKGROUNDS = {
        bigSur: {
            type: 'radial',
            colors: [
                { pos: 0, color: '#ff6b9d' },
                { pos: 0.3, color: '#c44569' },
                { pos: 0.5, color: '#6c5ce7' },
                { pos: 0.8, color: '#0c3483' },
                { pos: 1, color: '#1a1a2e' }
            ]
        },
        monterey: {
            type: 'radial',
            colors: [
                { pos: 0, color: '#00b894' },
                { pos: 0.25, color: '#00cec9' },
                { pos: 0.5, color: '#0984e3' },
                { pos: 0.8, color: '#6c5ce7' },
                { pos: 1, color: '#2d1b4e' }
            ]
        },
        ventura: {
            type: 'diagonal',
            colors: [
                { pos: 0, color: '#e17055' },
                { pos: 0.3, color: '#d63031' },
                { pos: 0.5, color: '#fd79a8' },
                { pos: 0.7, color: '#a855f7' },
                { pos: 1, color: '#1e3a5f' }
            ]
        },
        bloom: {
            type: 'radial',
            colors: [
                { pos: 0, color: '#74b9ff' },
                { pos: 0.3, color: '#0984e3' },
                { pos: 0.5, color: '#6c5ce7' },
                { pos: 0.7, color: '#a855f7' },
                { pos: 1, color: '#1a1a2e' }
            ]
        },
        sonoma: {
            type: 'diagonal',
            colors: [
                { pos: 0, color: '#fdcb6e' },
                { pos: 0.25, color: '#f39c12' },
                { pos: 0.5, color: '#e74c3c' },
                { pos: 0.75, color: '#9b59b6' },
                { pos: 1, color: '#2c3e50' }
            ]
        },
        midnight: {
            type: 'radial',
            colors: [
                { pos: 0, color: '#2c3e50' },
                { pos: 0.5, color: '#1a1a2e' },
                { pos: 1, color: '#0a0a0f' }
            ]
        }
    };

    _getBackgroundGradient() {
        const c = this.canvas;
        const ctx = this.ctx;
        const key = `${this.background}_${c.width}_${c.height}`;
        if (this._cachedBgKey === key && this._cachedBg) return this._cachedBg;

        const bgConfig = StudioEngine.BACKGROUNDS[this.background] || StudioEngine.BACKGROUNDS.bigSur;
        let gradient;
        if (bgConfig.type === 'radial') {
            gradient = ctx.createRadialGradient(
                c.width * 0.3, c.height * 0.3, 0,
                c.width * 0.5, c.height * 0.5, c.width * 0.8
            );
        } else {
            gradient = ctx.createLinearGradient(0, 0, c.width, c.height);
        }
        bgConfig.colors.forEach(({ pos, color }) => gradient.addColorStop(pos, color));
        this._cachedBg = gradient;
        this._cachedBgKey = key;
        return gradient;
    }

    drawFrame() {
        const ctx = this.ctx;
        const v = this.video;
        const curTimeSec = v?.currentTime || 0;

        const isVideoReady = v && (v.readyState >= 1 || v.videoWidth > 0 || (v.duration > 0 && v.currentTime >= 0));

        renderFrame(
            ctx,
            curTimeSec,
            isVideoReady ? v : null,
            {
                focusSegments: this.focusSegments || [],
                mouseSamples: this.mouseMoves || [],
                clicks: this.clicks || [],
            },
            {
                background: this.background,
                customBackgroundImage: this.customBackgroundImage,
                windowChrome: true,
                showCursor: this.showCursor,
                cursorTheme: this.cursorTheme || 'macos',
                cursorScale: this.cursorScale ?? 1,
                splineSmoothing: this.splineSmoothing !== false,
                zoomMagnification: (this.zoomLevel || 2.0) / 2.0,
                clickRipples: true,
                tiltAngle: this.tiltAngle ?? 3.5,
                connectedZooms: this.connectedZooms !== false,
                webcamSource: this.webcamVideo && this.webcamVideo.readyState >= 2 ? this.webcamVideo : null,
                webcamSettings: {
                    ...this.webcamSettings,
                    reactiveScale: this.reactiveWebcam !== false,
                },
                captions: this.captions || [],
                captionsEnabled: this.captionsEnabled,
                annotations: this.annotations || [],
            }
        );
    }

    dispose() {
        this.pause();
        cancelAnimationFrame(this.animationFrame);
        if (this.video?.src) URL.revokeObjectURL(this.video.src);
        this.video.onloadedmetadata = null;
        this.video.onplay = null;
        this.video.onpause = null;
        this.video.onended = null;
        this.video.onseeked = null;
        this.video.ontimeupdate = null;
        if (this.webcamVideo) {
            if (this.webcamVideo.src) URL.revokeObjectURL(this.webcamVideo.src);
            this.webcamVideo.removeAttribute('src');
            this.webcamVideo.load();
            this.webcamVideo = null;
        }
    }

    setCursorTheme(theme) {
        this.cursorTheme = theme;
        this.drawFrame();
    }

    setCursorScale(scale) {
        this.cursorScale = Math.max(0.2, Math.min(3.0, scale));
        this.drawFrame();
    }

    setSplineSmoothing(enabled) {
        this.splineSmoothing = Boolean(enabled);
        this.drawFrame();
    }

    setTiltAngle(angle) {
        this.tiltAngle = angle;
        this.drawFrame();
    }

    setConnectedZooms(enabled) {
        this.connectedZooms = enabled;
        this.drawFrame();
    }

    setReactiveWebcam(enabled) {
        this.reactiveWebcam = enabled;
        this.drawFrame();
    }

    setCaptions(captions) {
        this.captions = captions;
        this.drawFrame();
    }

    setAnnotations(annotations) {
        this.annotations = annotations;
        this.drawFrame();
    }

    setWebcamSettings(settings) {
        this.webcamSettings = { ...this.webcamSettings, ...settings };
        this.drawFrame();
    }

    setCustomBackgroundImage(img) {
        this.customBackgroundImage = img;
        this.drawFrame();
    }

    setBackground(bg) {
        this.background = bg;
        this.drawFrame();
    }

    setAspectRatio(aspectRatio = '16:9') {
        this.aspectRatio = aspectRatio;
        if (aspectRatio === '9:16') {
            this.canvas.width = 1080;
            this.canvas.height = 1920;
        } else if (aspectRatio === '1:1') {
            this.canvas.width = 1080;
            this.canvas.height = 1080;
        } else if (aspectRatio === '4:5') {
            this.canvas.width = 1080;
            this.canvas.height = 1350;
        } else {
            // 16:9
            this.canvas.width = 1920;
            this.canvas.height = 1080;
        }
        this._cachedBg = null;
        this.drawFrame();
    }

    drawClickRing(ctx, x, y, progress) {
        ctx.save();
        const radius = 8 + progress * 20;
        const alpha = (1 - progress) * 0.5;
        ctx.beginPath();
        ctx.arc(x, y, radius, 0, Math.PI * 2);
        ctx.strokeStyle = `rgba(255, 255, 255, ${alpha})`;
        ctx.lineWidth = 2 * (1 - progress * 0.5);
        ctx.stroke();
        ctx.beginPath();
        ctx.arc(x, y, radius * 0.5, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(255, 255, 255, ${alpha * 0.3})`;
        ctx.fill();
        ctx.restore();
    }

    drawCursor(ctx, x, y, motion = 0, clickProgress = 0) {
        ctx.save();
        ctx.translate(x, y);

        const clickScale = clickProgress > 0 ? 1 - clickProgress * 0.2 : 1;
        ctx.scale(clickScale, clickScale);

        const motionScale = 1 + motion * 0.12;
        ctx.scale(1, motionScale);

        ctx.shadowColor = 'rgba(0,0,0,0.5)';
        ctx.shadowBlur = 8 + motion * 12;
        ctx.shadowOffsetX = 2;
        ctx.shadowOffsetY = 2;

        // macOS-style pointer cursor
        ctx.beginPath();
        ctx.moveTo(0, 0);
        ctx.lineTo(0, 20);
        ctx.lineTo(5, 15);
        ctx.lineTo(9, 22);
        ctx.lineTo(12, 20);
        ctx.lineTo(8, 13);
        ctx.lineTo(14, 13);
        ctx.closePath();

        ctx.strokeStyle = '#ffffff';
        ctx.lineWidth = 2;
        ctx.stroke();

        ctx.fillStyle = '#000000';
        ctx.fill();

        ctx.restore();
    }

    roundRect(ctx, x, y, w, h, r) {
        ctx.beginPath();
        ctx.roundRect(x, y, w, h, r);
        ctx.closePath();
    }

    // --- EXPORT FUNCTION (MP4 via WebCodecs, WebM fallback) ---
    async exportVideo(onProgress, options = {}) {
        const { format = 'mp4', resolution = '1080p' } = options;

        if (format === 'webm') {
            return await this._exportWebM(onProgress, resolution);
        }

        // Try WebCodecs MP4 first (no ffmpeg, hardware-accelerated)
        if (typeof VideoEncoder !== 'undefined') {
            try {
                return await this._exportMP4(onProgress, resolution);
            } catch (e) {
                console.warn('[Studio] WebCodecs MP4 export failed, falling back to WebM:', e.message);
            }
        }
        // Fallback: WebM via MediaRecorder
        return await this._exportWebM(onProgress, resolution);
    }

    // --- WebCodecs + mp4-muxer → direct MP4 blob (no ffmpeg) ---
    async _exportMP4(onProgress, resolution = '1080p') {
        const { Muxer, ArrayBufferTarget } = await import('mp4-muxer');

        this.video.pause();
        this.video.currentTime = this.trimStart || 0;
        this.camera = { x: 0.5, y: 0.5, scale: 1 };
        await this._generateSegments();
        await new Promise(r => setTimeout(r, 300));

        const exportDuration = (this.trimEnd || this.videoDuration) - (this.trimStart || 0);
        const fps = 60;

        let width = 1920;
        let height = 1080;
        if (resolution === '4k') {
            width = 3840;
            height = 2160;
        } else if (resolution === '720p') {
            width = 1280;
            height = 720;
        }

        const origW = this.canvas.width;
        const origH = this.canvas.height;
        this.canvas.width = width;
        this.canvas.height = height;

        // Precompute frames in Rust
        if (this.isTauri && this.tauriReady) {
            try {
                this.precomputedFrames = await this.tauriInvoke('precompute_frames', {
                    segments: this.zoomSegments,
                    moves: (this.mouseMoves || []).map(m => ({ time: m.time, x: m.x, y: m.y })),
                    clicks: this.clicks.map(c => ({ time: c.time, x: c.x, y: c.y, down: true })),
                    durationMs: exportDuration * 1000,
                    fps,
                });
                console.log('[Studio] Precomputed', this.precomputedFrames.length, 'frames for export');
            } catch (e) {
                console.error('[Studio] Precompute failed:', e);
                this.precomputedFrames = null;
            }
        }

        const totalFrames = Math.ceil(exportDuration * fps);
        const frameDurationUs = 1_000_000 / fps;

        // Target bitrate: scale with resolution for consistent quality
        const isHD = width >= 1920;
        const targetBitrate = isHD ? 30_000_000 : 15_000_000; // 30Mbps for 1080p+, 15 for lower

        // Find a supported H.264 codec — try highest profile first (best quality)
        const profiles = ['avc1.640028', 'avc1.4d001f', 'avc1.42001f'];
        let codecConfig = null;
        for (const codec of profiles) {
            try {
                const support = await VideoEncoder.isConfigSupported({
                    codec, width, height,
                    bitrate: targetBitrate,
                    bitrateMode: 'constant',
                    framerate: fps,
                    latencyMode: 'quality',
                    hardwareAcceleration: 'prefer-hardware',
                    avc: { format: 'avc' },
                });
                if (support.supported) {
                    codecConfig = support.config;
                    console.log('[Studio] Using H.264 profile:', codec);
                    break;
                }
            } catch { continue; }
        }
        if (!codecConfig) throw new Error('No supported H.264 profile');

        console.log('[Studio] Exporting MP4 via WebCodecs:', width, 'x', height, '@', fps, 'fps,', (targetBitrate / 1_000_000) + 'Mbps');

        // Extract & decode audio track from recorded blob for MP4 audio muxing
        let audioBuffer = null;
        let audioEncoder = null;
        let hasAacAudio = false;

        if (typeof AudioEncoder !== 'undefined' && (this.systemAudioUrl || this.micAudioUrl || this.blob)) {
            try {
                const AudioCtx = window.AudioContext || window.webkitAudioContext;
                if (AudioCtx) {
                    const tempCtx = new AudioCtx();
                    try {
                        const loadBuf = async (src) => {
                            if (!src) return null;
                            const buf = typeof src === 'string'
                                ? await fetch(src).then(r => r.arrayBuffer())
                                : await src.arrayBuffer();
                            return await tempCtx.decodeAudioData(buf);
                        };

                        const sysBuf = await loadBuf(this.systemAudioUrl);
                        const micBuf = await loadBuf(this.micAudioUrl);

                        const sVol = this.isSystemAudioMuted ? 0 : (this.systemAudioVolume ?? 1.0);
                        const mVol = this.isMicAudioMuted ? 0 : (this.micAudioVolume ?? 1.2);
                        const autoDuck = this.autoDuck ?? true;

                        if (sysBuf && micBuf) {
                            const numChannels = Math.max(sysBuf.numberOfChannels, micBuf.numberOfChannels, 2);
                            const length = Math.max(sysBuf.length, micBuf.length);
                            const sampleRate = sysBuf.sampleRate;
                            audioBuffer = tempCtx.createBuffer(numChannels, length, sampleRate);

                            for (let ch = 0; ch < numChannels; ch++) {
                                const out = audioBuffer.getChannelData(ch);
                                const s = ch < sysBuf.numberOfChannels ? sysBuf.getChannelData(ch) : sysBuf.getChannelData(0);
                                const m = ch < micBuf.numberOfChannels ? micBuf.getChannelData(ch) : micBuf.getChannelData(0);
                                let duckGain = 1.0;
                                for (let i = 0; i < length; i++) {
                                    const mVal = i < m.length ? m[i] * mVol : 0;
                                    const isVoiceActive = Math.abs(mVal) > 0.035;
                                    const targetDuck = (autoDuck && isVoiceActive) ? 0.30 : 1.0;
                                    duckGain += (targetDuck - duckGain) * 0.005; // smooth anti-pop gain transition
                                    const sVal = i < s.length ? s[i] * sVol * duckGain : 0;
                                    out[i] = Math.max(-1, Math.min(1, sVal + mVal));
                                }
                            }
                        } else if (sysBuf) {
                            const numChannels = sysBuf.numberOfChannels;
                            audioBuffer = tempCtx.createBuffer(numChannels, sysBuf.length, sysBuf.sampleRate);
                            for (let ch = 0; ch < numChannels; ch++) {
                                const out = audioBuffer.getChannelData(ch);
                                const s = sysBuf.getChannelData(ch);
                                for (let i = 0; i < sysBuf.length; i++) {
                                    out[i] = Math.max(-1, Math.min(1, s[i] * sVol));
                                }
                            }
                        } else if (micBuf) {
                            const numChannels = micBuf.numberOfChannels;
                            audioBuffer = tempCtx.createBuffer(numChannels, micBuf.length, micBuf.sampleRate);
                            for (let ch = 0; ch < numChannels; ch++) {
                                const out = audioBuffer.getChannelData(ch);
                                const m = micBuf.getChannelData(ch);
                                for (let i = 0; i < micBuf.length; i++) {
                                    out[i] = Math.max(-1, Math.min(1, m[i] * mVol));
                                }
                            }
                        } else if (this.blob) {
                            audioBuffer = await loadBuf(this.blob);
                        }

                        if (audioBuffer && audioBuffer.length > 0) {
                            const aacCheck = await AudioEncoder.isConfigSupported({
                                codec: 'mp4a.40.2',
                                sampleRate: audioBuffer.sampleRate,
                                numberOfChannels: Math.min(2, audioBuffer.numberOfChannels),
                                bitrate: 192_000,
                            });
                            hasAacAudio = Boolean(aacCheck && aacCheck.supported);
                            console.log('[Studio] Decoded audio for export:', audioBuffer.duration.toFixed(2), 's, AAC supported:', hasAacAudio);
                        }
                    } catch (decodeErr) {
                        console.log('[Studio] No decodable audio track in source media:', decodeErr.message);
                    } finally {
                        try { await tempCtx.close(); } catch (e) {}
                    }
                }
            } catch (audioErr) {
                console.warn('[Studio] Audio extraction notice:', audioErr);
            }
        }

        const target = new ArrayBufferTarget();
        const muxerOptions = {
            target,
            video: { codec: 'avc', width, height },
            fastStart: 'in-memory',
        };

        if (hasAacAudio && audioBuffer) {
            muxerOptions.audio = {
                codec: 'aac',
                numberOfChannels: Math.min(2, audioBuffer.numberOfChannels),
                sampleRate: audioBuffer.sampleRate,
            };
        }

        const muxer = new Muxer(muxerOptions);

        return new Promise((resolve, reject) => {
            const encoder = new VideoEncoder({
                output: (chunk, meta) => muxer.addVideoChunk(chunk, meta),
                error: (e) => reject(e),
            });
            encoder.configure({
                ...codecConfig,
                hardwareAcceleration: 'prefer-hardware',
                latencyMode: 'quality',
                bitrateMode: 'constant',
                bitrate: targetBitrate,
            });

            // If AAC audio is available, initialize AudioEncoder and encode all audio packets
            if (hasAacAudio && audioBuffer) {
                try {
                    const numChannels = Math.min(2, audioBuffer.numberOfChannels);
                    const sampleRate = audioBuffer.sampleRate;

                    audioEncoder = new AudioEncoder({
                        output: (chunk, meta) => muxer.addAudioChunk(chunk, meta),
                        error: (e) => console.error('[Studio] Audio encoder error:', e),
                    });
                    audioEncoder.configure({
                        codec: 'mp4a.40.2',
                        sampleRate,
                        numberOfChannels: numChannels,
                        bitrate: 192_000,
                    });

                    // Sliced trimmed audio
                    const startSample = Math.max(0, Math.floor((this.trimStart || 0) * sampleRate));
                    const endSample = Math.min(audioBuffer.length, Math.ceil((this.trimEnd || this.videoDuration) * sampleRate));

                    if (endSample > startSample) {
                        const ch0 = audioBuffer.getChannelData(0);
                        const ch1 = numChannels > 1 ? audioBuffer.getChannelData(1) : ch0;
                        const CHUNK_SIZE = 1024;
                        let offset = startSample;

                        while (offset < endSample) {
                            const frames = Math.min(CHUNK_SIZE, endSample - offset);
                            const planar = new Float32Array(frames * numChannels);
                            planar.set(ch0.subarray(offset, offset + frames), 0);
                            if (numChannels > 1) {
                                planar.set(ch1.subarray(offset, offset + frames), frames);
                            }

                            const timestampUs = Math.round(((offset - startSample) / sampleRate) * 1_000_000);
                            const audioData = new AudioData({
                                format: 'f32-planar',
                                sampleRate,
                                numberOfFrames: frames,
                                numberOfChannels: numChannels,
                                timestamp: timestampUs,
                                data: planar,
                            });
                            audioEncoder.encode(audioData);
                            audioData.close();

                            offset += frames;
                        }
                    }
                } catch (audioEncErr) {
                    console.warn('[Studio] Audio encoding failed, exporting video-only:', audioEncErr);
                    audioEncoder = null;
                }
            }

            let frameIndex = 0;
            this.video.currentTime = this.trimStart || 0;

            const seekAndRender = () => {
                return new Promise(seekResolve => {
                    const targetTime = (this.trimStart || 0) + (frameIndex / fps);
                    if (targetTime >= (this.trimEnd || this.videoDuration) || frameIndex >= totalFrames) {
                        seekResolve(false);
                        return;
                    }

                    this.video.currentTime = targetTime;
                    if (this.webcamVideo) {
                        this.webcamVideo.currentTime = targetTime;
                    }
                    const onSeeked = () => {
                        this.video.removeEventListener('seeked', onSeeked);

                        // Apply precomputed or live camera state
                        if (this.precomputedFrames && frameIndex < this.precomputedFrames.length) {
                            const state = this.precomputedFrames[frameIndex];
                            this.camera = { x: state.zoom.x, y: state.zoom.y, scale: state.zoom.scale };
                            this.cursorState = state.cursor;
                        } else {
                            this.updateCamera();
                        }
                        this.drawFrame();

                        // Encode the canvas frame
                        const timestamp = Math.round(frameIndex * frameDurationUs);
                        const frame = new VideoFrame(this.canvas, {
                            timestamp,
                            duration: Math.round(frameDurationUs),
                        });
                        // Keyframe every 1 second for better seeking + quality
                        encoder.encode(frame, { keyFrame: frameIndex % fps === 0 });
                        frame.close();

                        frameIndex++;
                        if (onProgress) {
                            const p = Math.min(frameIndex / totalFrames, 1);
                            if (isFinite(p)) onProgress(p);
                        }
                        seekResolve(true);
                    };
                    this.video.addEventListener('seeked', onSeeked);
                });
            };

            const processFrames = async () => {
                try {
                    while (true) {
                        const hasMore = await seekAndRender();
                        if (!hasMore) break;
                    }

                    await encoder.flush();
                    encoder.close();

                    if (audioEncoder) {
                        try {
                            await audioEncoder.flush();
                            audioEncoder.close();
                        } catch (aeFlushErr) {
                            console.warn('[Studio] AudioEncoder flush notice:', aeFlushErr);
                        }
                    }

                    muxer.finalize();

                    this.precomputedFrames = null;
                    const mp4Blob = new Blob([target.buffer], { type: 'video/mp4' });
                    console.log('[Studio] MP4 export complete:', (mp4Blob.size / 1024 / 1024).toFixed(1), 'MB');
                    resolve(mp4Blob);
                } catch (e) {
                    reject(e);
                } finally {
                    this.canvas.width = origW;
                    this.canvas.height = origH;
                    this.drawFrame();
                }
            };

            processFrames();
        });
    }

    // --- WebM fallback via MediaRecorder ---
    async _exportWebM(onProgress, resolution = '1080p') {
        this.video.pause();
        this.video.currentTime = this.trimStart || 0;
        this.camera = { x: 0.5, y: 0.5, scale: 1 };
        await this._generateSegments();
        await new Promise(r => setTimeout(r, 300));

        const exportDuration = (this.trimEnd || this.videoDuration) - (this.trimStart || 0);
        const fps = 60;

        let width = 1920;
        let height = 1080;
        if (resolution === '4k') {
            width = 3840;
            height = 2160;
        } else if (resolution === '720p') {
            width = 1280;
            height = 720;
        }

        const origW = this.canvas.width;
        const origH = this.canvas.height;
        this.canvas.width = width;
        this.canvas.height = height;

        // Precompute frames in Rust
        if (this.isTauri && this.tauriReady) {
            try {
                this.precomputedFrames = await this.tauriInvoke('precompute_frames', {
                    segments: this.zoomSegments,
                    moves: (this.mouseMoves || []).map(m => ({ time: m.time, x: m.x, y: m.y })),
                    clicks: this.clicks.map(c => ({ time: c.time, x: c.x, y: c.y, down: true })),
                    durationMs: exportDuration * 1000,
                    fps,
                });
                console.log('[Studio] Precomputed', this.precomputedFrames.length, 'frames for export');
            } catch (e) {
                console.error('[Studio] Precompute failed:', e);
                this.precomputedFrames = null;
            }
        }

        const chunks = [];
        const mimeType = MediaRecorder.isTypeSupported('video/webm;codecs=vp8,opus')
            ? 'video/webm;codecs=vp8,opus'
            : 'video/webm';

        const stream = this.canvas.captureStream(0);
        if (this.video.captureStream) {
            try {
                const videoStream = this.video.captureStream();
                videoStream.getAudioTracks().forEach(track => stream.addTrack(track));
            } catch (e) {
                console.log('[Studio] Could not capture audio:', e);
            }
        }

        const rec = new MediaRecorder(stream, { mimeType, videoBitsPerSecond: 20_000_000 });
        rec.ondataavailable = e => { if (e.data.size > 0) chunks.push(e.data); };

        return new Promise(async (resolve) => {
            rec.onstop = async () => {
                let blob = new Blob(chunks, { type: 'video/webm' });
                try {
                    const { fixWebmDuration } = await import('@fix-webm-duration/fix');
                    const fixed = await fixWebmDuration(blob, exportDuration * 1000);
                    if (fixed && fixed.size > 0) blob = fixed;
                } catch (e) {
                    console.warn('[Studio] WebM export duration fix notice:', e);
                }
                this.precomputedFrames = null;
                this.canvas.width = origW;
                this.canvas.height = origH;
                this.drawFrame();
                resolve(blob);
            };

            rec.start();
            this.video.play();
            this.isPlaying = true;
            let frameIndex = 0;

            const renderExport = () => {
                if (this.video.ended || this.video.currentTime >= (this.trimEnd || this.videoDuration)) {
                    this.isPlaying = false;
                    this.video.pause();
                    rec.stop();
                    return;
                }

                if (this.precomputedFrames && frameIndex < this.precomputedFrames.length) {
                    const state = this.precomputedFrames[frameIndex];
                    this.camera = { x: state.zoom.x, y: state.zoom.y, scale: state.zoom.scale };
                    this.cursorState = state.cursor;
                } else {
                    this.updateCamera();
                }

                this.drawFrame();
                frameIndex++;

                const canvasTrack = stream.getVideoTracks().find(t => t.kind === 'video');
                if (canvasTrack?.requestFrame) canvasTrack.requestFrame();

                const currentTime = this.video.currentTime - (this.trimStart || 0);
                const progress = Math.min(Math.max(currentTime / exportDuration, 0), 1);
                if (onProgress && isFinite(progress)) onProgress(progress);

                requestAnimationFrame(renderExport);
            };

            renderExport();
        });
    }
}
